"use client";

import {
  Box,
  Container,
  Title,
  Text,
  Stack,
  Button,
  Group,
} from "@mantine/core";
import Link from "next/link";

export default function TermsPage() {
  return (
    <Box mt={20}>
      <Container size="md" py="xl">
        <Stack gap="lg">
          <Title order={1}>Terms of Service - Milegen.us</Title>

          <Box>
            <Title order={2} size="h4" mb="xs">
              1. Acceptance of Terms:
            </Title>
            <Text>
              By accessing and using Milegen.us (&quot;the Service&quot;), you
              agree to be bound by these Terms of Service (&quot;Terms&quot;).
              If you do not agree with any part of these Terms, you must not use
              the Service.
            </Text>
          </Box>

          <Box>
            <Title order={2} size="h4" mb="xs">
              2. Description of Service:
            </Title>
            <Text>
              Milegen.us provides a mileage log generation tool for
              informational and personal record-keeping purposes. The Service
              allows users to create, save, print, and download mileage logs.
            </Text>
          </Box>

          <Box>
            <Title order={2} size="h4" mb="xs">
              3. Informational Purpose Only:
            </Title>
            <Text>
              The mileage logs generated by Milegen.us are provided for
              informational purposes only. They are intended to assist users in
              tracking their mileage for personal records.
            </Text>
          </Box>

          <Box>
            <Title order={2} size="h4" mb="xs">
              4. No Tax or Legal Advice:
            </Title>
            <Text>
              Milegen.us does not provide tax, legal, or financial advice. The
              Service is not a substitute for professional advice from a
              qualified accountant, tax advisor, or attorney. You are solely
              responsible for ensuring the accuracy and completeness of your
              mileage records and for complying with all applicable tax laws and
              regulations.
            </Text>
          </Box>

          <Box>
            <Title order={2} size="h4" mb="xs">
              5. No Guarantee of Accuracy or Compliance:
            </Title>
            <Text>
              We make no guarantees regarding the accuracy, completeness, or
              suitability of the mileage logs generated by the Service for any
              specific purpose, including tax compliance. We do not warrant that
              the Service will meet your specific requirements or that it will
              be error-free.
            </Text>
          </Box>

          <Box>
            <Title order={2} size="h4" mb="xs">
              6. Limitation of Liability:
            </Title>
            <Text mb="md">
              <strong>No Liability for IRS or Other Authorities:</strong>{" "}
              Milegen.us shall not be liable for any penalties, fines, or other
              consequences resulting from the use or misuse of the Service,
              including any issues arising from audits or inquiries by the
              Internal Revenue Service (IRS) or any other governmental
              authority. You acknowledge that you are solely responsible for
              your compliance with all applicable laws and regulations.
            </Text>
            <Text mb="md">
              <strong>No Liability for Improper Use:</strong> Milegen.us is not
              responsible for any improper or unauthorized use of the Service.
              You agree to use the Service responsibly and in accordance with
              these Terms.
            </Text>
            <Text mb="md">
              <strong>Disclaimer of Warranties:</strong> The Service is provided
              &quot;as is&quot; and &quot;as available&quot; without any
              warranties of any kind, either express or implied. Milegen.us
              disclaims all warranties, including but not limited to, implied
              warranties of merchantability, fitness for a particular purpose,
              and non-infringement.
            </Text>
            <Text>
              <strong>Limitation of Damages:</strong> In no event shall
              Milegen.us be liable for any direct, indirect, incidental,
              consequential, or punitive damages arising out of or related to
              your use of the Service, even if Milegen.us has been advised of
              the possibility of such damages.
            </Text>
          </Box>

          <Box>
            <Title order={2} size="h4" mb="xs">
              7. User Responsibility:
            </Title>
            <Text>You are responsible for:</Text>
            <Text component="ul" pl="md">
              <li>
                Maintaining the confidentiality of your account information.
              </li>
              <li>
                Ensuring the accuracy of the data you input into the Service.
              </li>
              <li>
                Using the Service in compliance with all applicable laws and
                regulations.
              </li>
            </Text>
          </Box>

          <Box>
            <Title order={2} size="h4" mb="xs">
              8. Changes to Terms:
            </Title>
            <Text>
              Milegen.us reserves the right to modify these Terms at any time.
              We will notify you of any changes by posting the updated Terms on
              the Service. Your continued use of the Service after such changes
              constitutes your acceptance of the new Terms.
            </Text>
          </Box>

          <Box>
            <Title order={2} size="h4" mb="xs">
              9. Governing Law:
            </Title>
            <Text>
              These Terms shall be governed by and construed in accordance with
              the laws of the State of Texas, without regard to its conflict of
              law provisions.
            </Text>
          </Box>

          <Box>
            <Title order={2} size="h4" mb="xs">
              10. Contact Information:
            </Title>
            <Text>
              If you have any questions about these Terms, please contact us at
              support@milegen.us
            </Text>
          </Box>

          <Group justify="center" mt="xl">
            <Link href="/?signup=true">
              <Button>Back to Sign Up</Button>
            </Link>
          </Group>
        </Stack>
      </Container>
    </Box>
  );
}
