export const HOLIDAYS = {
  2023: [
    "2023-01-02",
    "2023-01-16",
    "2023-02-20",
    "2023-05-29",
    "2023-06-19",
    "2023-07-04",
    "2023-09-04",
    "2023-10-09",
    "2023-11-10",
    "2023-11-23",
    "2023-12-25",
  ],
  2024: [
    "2024-01-01",
    "2024-01-15",
    "2024-02-19",
    "2024-05-27",
    "2024-07-04",
    "2024-09-02",
    "2024-10-14",
    "2024-11-11",
    "2024-11-28",
    "2024-12-25",
  ],
  2025: [
    "2025-01-01",
    "2025-01-20",
    "2025-02-17",
    "2025-05-26",
    "2025-07-04",
    "2025-09-01",
    "2025-10-13",
    "2025-11-11",
    "2025-11-27",
    "2025-12-25",
  ],
  2026: [
    "2026-01-01",
    "2026-01-19",
    "2026-02-16",
    "2026-05-25",
    "2026-07-04",
    "2026-09-07",
    "2026-10-12",
    "2026-11-11",
    "2026-11-26",
    "2026-12-25",
  ],
  2027: [
    "2027-01-01",
    "2027-01-18",
    "2027-02-15",
    "2027-05-31",
    "2027-07-04",
    "2027-09-06",
    "2027-10-11",
    "2027-11-11",
    "2027-11-25",
    "2027-12-25",
  ],
  2028: [
    "2028-01-01",
    "2028-01-17",
    "2028-02-21",
    "2028-05-29",
    "2028-07-04",
    "2028-09-04",
    "2028-10-09",
    "2028-11-10",
    "2028-11-23",
    "2028-12-25",
  ],
  2029: [
    "2029-01-01",
    "2029-01-15",
    "2029-02-19",
    "2029-05-28",
    "2029-07-04",
    "2029-09-03",
    "2029-10-08",
    "2029-11-12",
    "2029-11-22",
    "2029-12-25",
  ],
  2030: [
    "2030-01-01",
    "2030-01-21",
    "2030-02-18",
    "2030-05-27",
    "2030-07-04",
    "2030-09-02",
    "2030-10-14",
    "2030-11-11",
    "2030-11-28",
    "2030-12-25",
  ],
};

// Standard business mileage deduction rates by year (dollars per mile)
// Source: IRS standard mileage rates
export const BUSINESS_MILEAGE_RATES = {
  2020: 0.575, // 57.5 cents per mile
  2021: 0.56, // 56 cents per mile
  2022: 0.585, // 58.5 cents per mile for first half, 62.5 cents per mile for second half (using lower value for safety)
  2023: 0.655, // 65.5 cents per mile
  2024: 0.67, // 67 cents per mile
  2025: 0.67, // Using 2024 rate as placeholder until IRS announces 2025 rate
  2026: 0.67, // Using 2024 rate as placeholder until IRS announces 2026 rate
  2027: 0.67, // Using 2024 rate as placeholder until IRS announces 2027 rate
  2028: 0.67, // Using 2024 rate as placeholder until IRS announces 2028 rate
  2029: 0.67, // Using 2024 rate as placeholder until IRS announces 2029 rate
  2030: 0.67, // Using 2024 rate as placeholder until IRS announces 2030 rate
};

// Gets the business mileage rate for a given year
// If the year is not found, returns the most recent known rate
export function getBusinessMileageRate(year: number): number {
  if (year in BUSINESS_MILEAGE_RATES) {
    return BUSINESS_MILEAGE_RATES[year as keyof typeof BUSINESS_MILEAGE_RATES];
  }

  // If the year is not found, use the most recent year's rate
  const years = Object.keys(BUSINESS_MILEAGE_RATES).map(Number);
  const mostRecentYear = Math.max(...years);
  return BUSINESS_MILEAGE_RATES[
    mostRecentYear as keyof typeof BUSINESS_MILEAGE_RATES
  ];
}

export const MAX_FREE_ENTRIES = 10;

// Comprehensive vehicle makes and models - alphabetized for easier selection
export const VEHICLE_MAKES = [
  { value: "acura", label: "Acura" },
  { value: "alfa-romeo", label: "Alfa Romeo" },
  { value: "aston-martin", label: "Aston Martin" },
  { value: "audi", label: "Audi" },
  { value: "bentley", label: "Bentley" },
  { value: "bmw", label: "BMW" },
  { value: "buick", label: "Buick" },
  { value: "cadillac", label: "Cadillac" },
  { value: "chevrolet", label: "Chevrolet" },
  { value: "chrysler", label: "Chrysler" },
  { value: "dodge", label: "Dodge" },
  { value: "ferrari", label: "Ferrari" },
  { value: "fiat", label: "Fiat" },
  { value: "ford", label: "Ford" },
  { value: "genesis", label: "Genesis" },
  { value: "gmc", label: "GMC" },
  { value: "honda", label: "Honda" },
  { value: "hyundai", label: "Hyundai" },
  { value: "infiniti", label: "Infiniti" },
  { value: "jaguar", label: "Jaguar" },
  { value: "jeep", label: "Jeep" },
  { value: "kia", label: "Kia" },
  { value: "lamborghini", label: "Lamborghini" },
  { value: "land-rover", label: "Land Rover" },
  { value: "lexus", label: "Lexus" },
  { value: "lincoln", label: "Lincoln" },
  { value: "maserati", label: "Maserati" },
  { value: "mazda", label: "Mazda" },
  { value: "mercedes", label: "Mercedes-Benz" },
  { value: "mini", label: "MINI" },
  { value: "mitsubishi", label: "Mitsubishi" },
  { value: "nissan", label: "Nissan" },
  { value: "porsche", label: "Porsche" },
  { value: "ram", label: "RAM" },
  { value: "rivian", label: "Rivian" },
  { value: "rolls-royce", label: "Rolls-Royce" },
  { value: "subaru", label: "Subaru" },
  { value: "tesla", label: "Tesla" },
  { value: "toyota", label: "Toyota" },
  { value: "volkswagen", label: "Volkswagen" },
  { value: "volvo", label: "Volvo" },
];

// Models by make - alphabetized for easier selection
export const VEHICLE_MODELS: Record<string, { value: string; label: string }[]> = {
  acura: [
    { value: "ilx", label: "ILX" },
    { value: "integra", label: "Integra" },
    { value: "mdx", label: "MDX" },
    { value: "nsx", label: "NSX" },
    { value: "rdx", label: "RDX" },
    { value: "tlx", label: "TLX" },
  ],
  "alfa-romeo": [
    { value: "4c", label: "4C" },
    { value: "giulia", label: "Giulia" },
    { value: "stelvio", label: "Stelvio" },
    { value: "tonale", label: "Tonale" },
  ],
  "aston-martin": [
    { value: "db11", label: "DB11" },
    { value: "db12", label: "DB12" },
    { value: "dbx", label: "DBX" },
    { value: "vantage", label: "Vantage" },
  ],
  audi: [
    { value: "a3", label: "A3" },
    { value: "a4", label: "A4" },
    { value: "a5", label: "A5" },
    { value: "a6", label: "A6" },
    { value: "a7", label: "A7" },
    { value: "a8", label: "A8" },
    { value: "e-tron", label: "e-tron" },
    { value: "e-tron-gt", label: "e-tron GT" },
    { value: "q3", label: "Q3" },
    { value: "q4-e-tron", label: "Q4 e-tron" },
    { value: "q5", label: "Q5" },
    { value: "q7", label: "Q7" },
    { value: "q8", label: "Q8" },
    { value: "r8", label: "R8" },
    { value: "rs5", label: "RS5" },
    { value: "rs7", label: "RS7" },
    { value: "s4", label: "S4" },
    { value: "s5", label: "S5" },
    { value: "tt", label: "TT" },
  ],
  bentley: [
    { value: "bentayga", label: "Bentayga" },
    { value: "continental", label: "Continental" },
    { value: "flying-spur", label: "Flying Spur" },
  ],
  bmw: [
    { value: "1-series", label: "1 Series" },
    { value: "2-series", label: "2 Series" },
    { value: "3-series", label: "3 Series" },
    { value: "4-series", label: "4 Series" },
    { value: "5-series", label: "5 Series" },
    { value: "6-series", label: "6 Series" },
    { value: "7-series", label: "7 Series" },
    { value: "8-series", label: "8 Series" },
    { value: "i3", label: "i3" },
    { value: "i4", label: "i4" },
    { value: "i7", label: "i7" },
    { value: "i8", label: "i8" },
    { value: "ix", label: "iX" },
    { value: "m2", label: "M2" },
    { value: "m3", label: "M3" },
    { value: "m4", label: "M4" },
    { value: "m5", label: "M5" },
    { value: "m8", label: "M8" },
    { value: "x1", label: "X1" },
    { value: "x2", label: "X2" },
    { value: "x3", label: "X3" },
    { value: "x4", label: "X4" },
    { value: "x5", label: "X5" },
    { value: "x6", label: "X6" },
    { value: "x7", label: "X7" },
    { value: "z4", label: "Z4" },
  ],
  buick: [
    { value: "enclave", label: "Enclave" },
    { value: "encore", label: "Encore" },
    { value: "encore-gx", label: "Encore GX" },
    { value: "envision", label: "Envision" },
  ],
  cadillac: [
    { value: "ct4", label: "CT4" },
    { value: "ct5", label: "CT5" },
    { value: "escalade", label: "Escalade" },
    { value: "lyriq", label: "LYRIQ" },
    { value: "xt4", label: "XT4" },
    { value: "xt5", label: "XT5" },
    { value: "xt6", label: "XT6" },
  ],
  chevrolet: [
    { value: "blazer", label: "Blazer" },
    { value: "bolt", label: "Bolt" },
    { value: "camaro", label: "Camaro" },
    { value: "colorado", label: "Colorado" },
    { value: "corvette", label: "Corvette" },
    { value: "equinox", label: "Equinox" },
    { value: "malibu", label: "Malibu" },
    { value: "silverado", label: "Silverado" },
    { value: "spark", label: "Spark" },
    { value: "suburban", label: "Suburban" },
    { value: "tahoe", label: "Tahoe" },
    { value: "trailblazer", label: "Trailblazer" },
    { value: "traverse", label: "Traverse" },
    { value: "trax", label: "Trax" },
  ],
  chrysler: [
    { value: "300", label: "300" },
    { value: "pacifica", label: "Pacifica" },
  ],
  dodge: [
    { value: "challenger", label: "Challenger" },
    { value: "charger", label: "Charger" },
    { value: "durango", label: "Durango" },
    { value: "hornet", label: "Hornet" },
  ],
  ferrari: [
    { value: "296", label: "296" },
    { value: "812", label: "812" },
    { value: "f8", label: "F8" },
    { value: "portofino", label: "Portofino" },
    { value: "purosangue", label: "Purosangue" },
    { value: "roma", label: "Roma" },
    { value: "sf90", label: "SF90" },
  ],
  fiat: [
    { value: "500", label: "500" },
    { value: "500x", label: "500X" },
  ],
  ford: [
    { value: "bronco", label: "Bronco" },
    { value: "bronco-sport", label: "Bronco Sport" },
    { value: "edge", label: "Edge" },
    { value: "escape", label: "Escape" },
    { value: "expedition", label: "Expedition" },
    { value: "explorer", label: "Explorer" },
    { value: "f-150", label: "F-150" },
    { value: "f-250", label: "F-250" },
    { value: "f-350", label: "F-350" },
    { value: "maverick", label: "Maverick" },
    { value: "mustang", label: "Mustang" },
    { value: "mustang-mach-e", label: "Mustang Mach-E" },
    { value: "ranger", label: "Ranger" },
    { value: "transit", label: "Transit" },
  ],
  genesis: [
    { value: "g70", label: "G70" },
    { value: "g80", label: "G80" },
    { value: "g90", label: "G90" },
    { value: "gv60", label: "GV60" },
    { value: "gv70", label: "GV70" },
    { value: "gv80", label: "GV80" },
  ],
  gmc: [
    { value: "acadia", label: "Acadia" },
    { value: "canyon", label: "Canyon" },
    { value: "hummer-ev", label: "Hummer EV" },
    { value: "sierra", label: "Sierra" },
    { value: "terrain", label: "Terrain" },
    { value: "yukon", label: "Yukon" },
  ],
  honda: [
    { value: "accord", label: "Accord" },
    { value: "civic", label: "Civic" },
    { value: "cr-v", label: "CR-V" },
    { value: "hr-v", label: "HR-V" },
    { value: "odyssey", label: "Odyssey" },
    { value: "passport", label: "Passport" },
    { value: "pilot", label: "Pilot" },
    { value: "ridgeline", label: "Ridgeline" },
  ],
  hyundai: [
    { value: "elantra", label: "Elantra" },
    { value: "ioniq", label: "IONIQ" },
    { value: "ioniq-5", label: "IONIQ 5" },
    { value: "ioniq-6", label: "IONIQ 6" },
    { value: "kona", label: "Kona" },
    { value: "palisade", label: "Palisade" },
    { value: "santa-cruz", label: "Santa Cruz" },
    { value: "santa-fe", label: "Santa Fe" },
    { value: "sonata", label: "Sonata" },
    { value: "tucson", label: "Tucson" },
    { value: "venue", label: "Venue" },
  ],
  infiniti: [
    { value: "q50", label: "Q50" },
    { value: "q60", label: "Q60" },
    { value: "qx50", label: "QX50" },
    { value: "qx55", label: "QX55" },
    { value: "qx60", label: "QX60" },
    { value: "qx80", label: "QX80" },
  ],
  jaguar: [
    { value: "e-pace", label: "E-PACE" },
    { value: "f-pace", label: "F-PACE" },
    { value: "f-type", label: "F-TYPE" },
    { value: "i-pace", label: "I-PACE" },
    { value: "xe", label: "XE" },
    { value: "xf", label: "XF" },
  ],
  jeep: [
    { value: "cherokee", label: "Cherokee" },
    { value: "compass", label: "Compass" },
    { value: "gladiator", label: "Gladiator" },
    { value: "grand-cherokee", label: "Grand Cherokee" },
    { value: "renegade", label: "Renegade" },
    { value: "wagoneer", label: "Wagoneer" },
    { value: "wrangler", label: "Wrangler" },
  ],
  kia: [
    { value: "carnival", label: "Carnival" },
    { value: "ev6", label: "EV6" },
    { value: "ev9", label: "EV9" },
    { value: "forte", label: "Forte" },
    { value: "k5", label: "K5" },
    { value: "niro", label: "Niro" },
    { value: "rio", label: "Rio" },
    { value: "seltos", label: "Seltos" },
    { value: "sorento", label: "Sorento" },
    { value: "soul", label: "Soul" },
    { value: "sportage", label: "Sportage" },
    { value: "stinger", label: "Stinger" },
    { value: "telluride", label: "Telluride" },
  ],
  lamborghini: [
    { value: "aventador", label: "Aventador" },
    { value: "huracan", label: "Huracán" },
    { value: "revuelto", label: "Revuelto" },
    { value: "urus", label: "Urus" },
  ],
  "land-rover": [
    { value: "defender", label: "Defender" },
    { value: "discovery", label: "Discovery" },
    { value: "discovery-sport", label: "Discovery Sport" },
    { value: "range-rover", label: "Range Rover" },
    { value: "range-rover-evoque", label: "Range Rover Evoque" },
    { value: "range-rover-sport", label: "Range Rover Sport" },
    { value: "range-rover-velar", label: "Range Rover Velar" },
  ],
  lexus: [
    { value: "es", label: "ES" },
    { value: "gx", label: "GX" },
    { value: "is", label: "IS" },
    { value: "lc", label: "LC" },
    { value: "ls", label: "LS" },
    { value: "lx", label: "LX" },
    { value: "nx", label: "NX" },
    { value: "rc", label: "RC" },
    { value: "rx", label: "RX" },
    { value: "rz", label: "RZ" },
    { value: "tx", label: "TX" },
    { value: "ux", label: "UX" },
  ],
  lincoln: [
    { value: "aviator", label: "Aviator" },
    { value: "corsair", label: "Corsair" },
    { value: "nautilus", label: "Nautilus" },
    { value: "navigator", label: "Navigator" },
  ],
  maserati: [
    { value: "ghibli", label: "Ghibli" },
    { value: "grecale", label: "Grecale" },
    { value: "levante", label: "Levante" },
    { value: "mc20", label: "MC20" },
    { value: "quattroporte", label: "Quattroporte" },
  ],
  mazda: [
    { value: "cx-30", label: "CX-30" },
    { value: "cx-5", label: "CX-5" },
    { value: "cx-50", label: "CX-50" },
    { value: "cx-9", label: "CX-9" },
    { value: "cx-90", label: "CX-90" },
    { value: "mazda3", label: "Mazda3" },
    { value: "mazda6", label: "Mazda6" },
    { value: "mx-5", label: "MX-5 Miata" },
  ],
  mercedes: [
    { value: "a-class", label: "A-Class" },
    { value: "amg-gt", label: "AMG GT" },
    { value: "c-class", label: "C-Class" },
    { value: "cla", label: "CLA" },
    { value: "cls", label: "CLS" },
    { value: "e-class", label: "E-Class" },
    { value: "eqs", label: "EQS" },
    { value: "g-class", label: "G-Class" },
    { value: "gla", label: "GLA" },
    { value: "glb", label: "GLB" },
    { value: "glc", label: "GLC" },
    { value: "gle", label: "GLE" },
    { value: "gls", label: "GLS" },
    { value: "s-class", label: "S-Class" },
    { value: "sl", label: "SL" },
  ],
  mini: [
    { value: "clubman", label: "Clubman" },
    { value: "convertible", label: "Convertible" },
    { value: "countryman", label: "Countryman" },
    { value: "hardtop", label: "Hardtop" },
  ],
  mitsubishi: [
    { value: "eclipse-cross", label: "Eclipse Cross" },
    { value: "mirage", label: "Mirage" },
    { value: "outlander", label: "Outlander" },
    { value: "outlander-sport", label: "Outlander Sport" },
  ],
  nissan: [
    { value: "altima", label: "Altima" },
    { value: "ariya", label: "Ariya" },
    { value: "armada", label: "Armada" },
    { value: "frontier", label: "Frontier" },
    { value: "kicks", label: "Kicks" },
    { value: "leaf", label: "LEAF" },
    { value: "maxima", label: "Maxima" },
    { value: "murano", label: "Murano" },
    { value: "pathfinder", label: "Pathfinder" },
    { value: "rogue", label: "Rogue" },
    { value: "sentra", label: "Sentra" },
    { value: "titan", label: "Titan" },
    { value: "versa", label: "Versa" },
    { value: "z", label: "Z" },
  ],
  porsche: [
    { value: "718", label: "718" },
    { value: "911", label: "911" },
    { value: "cayenne", label: "Cayenne" },
    { value: "macan", label: "Macan" },
    { value: "panamera", label: "Panamera" },
    { value: "taycan", label: "Taycan" },
  ],
  ram: [
    { value: "1500", label: "1500" },
    { value: "2500", label: "2500" },
    { value: "3500", label: "3500" },
    { value: "promaster", label: "ProMaster" },
  ],
  rivian: [
    { value: "r1s", label: "R1S" },
    { value: "r1t", label: "R1T" },
  ],
  "rolls-royce": [
    { value: "cullinan", label: "Cullinan" },
    { value: "ghost", label: "Ghost" },
    { value: "phantom", label: "Phantom" },
    { value: "spectre", label: "Spectre" },
  ],
  subaru: [
    { value: "ascent", label: "Ascent" },
    { value: "brz", label: "BRZ" },
    { value: "crosstrek", label: "Crosstrek" },
    { value: "forester", label: "Forester" },
    { value: "impreza", label: "Impreza" },
    { value: "legacy", label: "Legacy" },
    { value: "outback", label: "Outback" },
    { value: "solterra", label: "Solterra" },
    { value: "wrx", label: "WRX" },
  ],
  tesla: [
    { value: "cybertruck", label: "Cybertruck" },
    { value: "model-3", label: "Model 3" },
    { value: "model-s", label: "Model S" },
    { value: "model-x", label: "Model X" },
    { value: "model-y", label: "Model Y" },
    { value: "roadster", label: "Roadster" },
  ],
  toyota: [
    { value: "4runner", label: "4Runner" },
    { value: "avalon", label: "Avalon" },
    { value: "bz4x", label: "bZ4X" },
    { value: "camry", label: "Camry" },
    { value: "corolla", label: "Corolla" },
    { value: "corolla-cross", label: "Corolla Cross" },
    { value: "crown", label: "Crown" },
    { value: "gr86", label: "GR86" },
    { value: "gr-corolla", label: "GR Corolla" },
    { value: "gr-supra", label: "GR Supra" },
    { value: "highlander", label: "Highlander" },
    { value: "land-cruiser", label: "Land Cruiser" },
    { value: "mirai", label: "Mirai" },
    { value: "prius", label: "Prius" },
    { value: "rav4", label: "RAV4" },
    { value: "sequoia", label: "Sequoia" },
    { value: "sienna", label: "Sienna" },
    { value: "tacoma", label: "Tacoma" },
    { value: "tundra", label: "Tundra" },
    { value: "venza", label: "Venza" },
  ],
  volkswagen: [
    { value: "arteon", label: "Arteon" },
    { value: "atlas", label: "Atlas" },
    { value: "atlas-cross-sport", label: "Atlas Cross Sport" },
    { value: "golf-gti", label: "Golf GTI" },
    { value: "golf-r", label: "Golf R" },
    { value: "id4", label: "ID.4" },
    { value: "jetta", label: "Jetta" },
    { value: "taos", label: "Taos" },
    { value: "tiguan", label: "Tiguan" },
  ],
  volvo: [
    { value: "c40", label: "C40" },
    { value: "ex30", label: "EX30" },
    { value: "ex90", label: "EX90" },
    { value: "s60", label: "S60" },
    { value: "s90", label: "S90" },
    { value: "v60", label: "V60" },
    { value: "v90", label: "V90" },
    { value: "xc40", label: "XC40" },
    { value: "xc60", label: "XC60" },
    { value: "xc90", label: "XC90" },
  ],
};

// Generate years (current year down to 1990)
export const VEHICLE_YEARS = Array.from({ length: new Date().getFullYear() - 1989 }, (_, i) => {
  const year = new Date().getFullYear() - i;
  return { value: year.toString(), label: year.toString() };
});
